### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by bobvann** [vickyg3/UrlPlayer#8]
It would be nice if you could update the hosted version of the UrlPlayer with latest changes, so that users can join the new functions of the player

**Comment by onigetoc** [comment]
I did one here with some modification.
Directe playing list.
Add media info, title and description.
http://scripts.toolurl.com/1-Chromecast/UrlPlayer-master/indexGC.html

**Comment by vickyg3** [comment]
Done, i've update http://movies.foamsnet.com/url with the latest changes.

**Comment by onigetoc** [comment]
Can you explain the update?

**Comment by vickyg3** [comment]
i have pulled the latest git head to movies.foamsnet.com. So whatever recent changes that were made should show up there.

**Comment by bobvann** [comment]
thank you!
